version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
          - .:/var/www
        ports:
          - "9000:9000"
        depends_on:
          - mysql

    webserver:
        image: nginx:latest
        container_name: nginx_web
        restart: unless-stopped
        ports:
          - "8000:80"
        volumes:
          - .:/var/www
          - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - app
    mysql:
        image: mysql:8.2
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
        - "3307:3306"
        volumes:
        - dbdata:/var/lib/mysql

volumes:
    dbdata:
